```{r setup, include = FALSE, warning = FALSE}

# load graphics libraries
    library(plyr)
    library(ggplot2)
    library(reshape2)
    library(tidyverse)
    library(knitr)
    library(kableExtra)
    library(plotly)
    library(stringr)
    library(bsselectR)
    library(lubridate)
    library(textclean)

    #setwd('/projects/gherman/OPT_callReport')

```


```{r}
prepare_init_df <- function(df, mri){
  
  #for the purposes of this report - only consider the first session of the baseline scan - might need to modify later if want to count followup
  mri <- subset(mri, mri$redcap_repeat_instrument =="optimum_neuro_mri")
  mri <- subset(mri, mri$redcap_event_name =="baseline_arm_6"|mri$redcap_event_name =="6_mth_fu_arm_6")

#merge mri and df dataframes
  df <- merge(df, mri, by=c('record_id', 'redcap_event_name'), all.x=TRUE)

#pull out site code from subject IDs
  df$site <- substring(df$record_id, 1, 2)

#make sure that site data is a factor
  df$site <- as.factor(df$site)
  sites <- factor(x = c('CU', 'LA', 'UP', 'UT', 'WU'), levels = c('CU', 'LA', 'UP', 'UT', 'WU'))
  


#make sure all site codes are uppercase
  df$site <- toupper(df$site)

#remove any sites that don't match expected site codes  
  df <- df[(df$site == 'CU' | df$site == 'LA' | df$site == 'UP' | df$site == 'UT' | df$site == 'WU'),]

#rename timepoint variable
  names(df)[names(df)=="redcap_event_name"] <- "timepoint"

#rename factors in timepoint variable
  levels(df$timepoint) <- c(levels(df$timepoint), "baseline", "6 mth FU", "24 mth FU") 
  df$timepoint[df$timepoint == "baseline_arm_6"]  <- "baseline"
  df$timepoint[df$timepoint == "6_mth_fu_arm_6"]  <- "6 mth FU" 
  df$timepoint[df$timepoint == "24_mth_fu_arm_6"]  <- "24 mth FU" 
  df$timepoint <- droplevels(df$timepoint, exclude = c("baseline_arm_6", "6_mth_fu_arm_6", "24_mth_fu_arm_6"))
  
  return(df)
}
```


```{r}
prepare_recruit_df <- function(recruit_df){

#make sure important dates are in date format
  recruit_df$dkefs_date <- as.Date(recruit_df$dkefs_date_admin, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to date format
  recruit_df$rbans_date <- as.Date(recruit_df$rbans_date_admin, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to date format

#get current date and add to dataframe
  recruit_df$currentYm <- Sys.Date() #add current sysdate to df
  recruit_df$currentYm_str <- as.character(substr(recruit_df$currentYm, 1, 7)) #store month and year, as character

#add column that indicates if consented, consent date, and if this month
 recruit_df$consented[is.na(recruit_df$meta_consent_date)] <- 0
 recruit_df$consented[is.na(recruit_df$consented)] <- 1
 recruit_df$meta_consent_date <- as.Date(recruit_df$meta_consent_date, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to date format
 recruit_df$meta_consent_mth <- as.character(substr(recruit_df$meta_consent_date, 1, 7)) #store month and year, as character
 recruit_df$meta_consent_mthT <- recruit_df$meta_consent_mth %in% recruit_df$currentYm_str #logical T or F- was consent this month?
 
#add column that indicates if completed, complete date, and if this month
 recruit_df$completed <- ifelse(recruit_df$meta_terminate_reason == 3, 1, 0)
 recruit_df$meta_terminate_date <- as.Date(recruit_df$meta_terminate_date, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to date format
 recruit_df$meta_terminate_mth <- as.character(substr(recruit_df$meta_terminate_date, 1, 7)) #store month and year, as character
 recruit_df$meta_terminate_mthT <- recruit_df$meta_terminate_mth %in% recruit_df$currentYm_str #logical T or F- was complete this month?
 recruit_df$meta_complete_mthT <- ifelse(recruit_df$completed == 1 & recruit_df$meta_terminate_mthT == TRUE, TRUE, FALSE)

#add column that indicates if terminated
 recruit_df$terminated <- ifelse(recruit_df$meta_terminate_reason == 3, 0, 1)

#add columns that indicate timepoint at which terminated (for reasons other than completion)
 #GABI note to self: I don't think this would work...
 recruit_df$terminate_baseline <- ifelse(recruit_df$meta_terminate_reason != 3 & recruit_df$timepoint == 'baseline', 1, NA)
 recruit_df$terminate_FU_06_MTH <- ifelse(recruit_df$meta_terminate_reason != 3 & recruit_df$timepoint == '6 mth FU', 1, NA)
 recruit_df$terminate_FU_24_MTH <- ifelse(recruit_df$meta_terminate_reason != 3 & recruit_df$timepoint == '24 mth FU', 1, NA)
 
 return(recruit_df)
}
```


```{r}
prepare_enroll_df <- function(enroll_df) {
#NOTE TO SELF FOR GABI: It seems like this is where enroll df starts only counting baseline. I think that I could just filter out 6 month follow up from baseline and calculate that way???  
#NOTE TO SELF FOR GABI: I JUST COMMENTED THIS OUT 
#take only baseline
 enroll_df <- enroll_df[(enroll_df$timepoint == 'baseline'),] 
 
#first, check if T1 complete, and if date is this month
  #note - here, 'complete' means just T1 complete
  names(enroll_df)[names(enroll_df) == "mr_t1"] <- "enroll_mri" #change name of status column
  names(enroll_df)[names(enroll_df) == "mr_date"] <- "enroll_mri_date" #change name of date column
  
  enroll_df$enroll_mri <- ifelse(enroll_df$enroll_mri == 1, 1, NA) #turn no to NA
  enroll_df$enroll_mri_date <- as.Date(enroll_df$enroll_mri_date, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to datetime format
  enroll_df$enroll_mri_mth <- as.character(substr(enroll_df$enroll_mri_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_mri_mthT <- enroll_df$enroll_mri_mth %in% enroll_df$currentYm_str #logical T or F- was MRI this month?

#second, check if blood complete, and if date is this month
  #note - here, 'complete' means that just the plasma is complete (don't care about serum)
  enroll_df$enroll_bld <- ifelse(enroll_df$plasma_blood_status == 1, 1, NA) #turn no and partial to NA
  enroll_df$enroll_bld_date <- substr(enroll_df$plasma_blood_date, 1, 11)#cut out the time contained in datetime
  enroll_df$enroll_bld_date <- as.Date(enroll_df$enroll_bld_date, format = "%Y-%m-%d", origin = "1970-01-01") #convert to datetime 
  enroll_df$enroll_bld_mth <- as.character(substr(enroll_df$enroll_bld_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_bld_mthT <- enroll_df$enroll_bld_mth %in% enroll_df$currentYm_str #logical T or F - was blood this month?    
  
#third, check if neuropsych complete, and if data is this month
  #note - here, 'complete' means rbans and dkefs done in entirity
  #make new columns with completion and date data for 2 assessments we care about - dkefs and rbans
  enroll_df$dkefs <- ifelse(enroll_df$dkefs_complete == 1, 1, NA) #turn no and partial to NA
  enroll_df$enroll_dkefs_date <- as.Date(enroll_df$dkefs_date_admin, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to datetime format
  enroll_df$enroll_dkefs_mth <- as.character(substr(enroll_df$enroll_dkefs_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_dkefs_mthT <- enroll_df$enroll_dkefs_mth %in% enroll_df$currentYm_str #logical T or F- was dkefs this month?

  enroll_df$rbans <- ifelse(enroll_df$rbans_complete == 1, 1, NA) #turn no and partial to NA
  enroll_df$enroll_rbans_date <- as.Date(enroll_df$rbans_date_admin, format = "%Y-%m-%d", origin = "1970-01-01") #convert date to datetime format
  enroll_df$enroll_rbans_mth <- as.character(substr(enroll_df$enroll_rbans_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_rbans_mthT <- enroll_df$enroll_rbans_mth %in% enroll_df$currentYm_str #logical T or F- was rbans this month?
  
  #take the sum of columns - want both of the central neuropsych assessments (dkefs, rbans) to be complete
  enroll_df[, c('dkefs', 'rbans')] <- sapply(enroll_df[, c('dkefs', 'rbans')], as.numeric) #change to numeric
  enroll_df$np_count <- rowSums(enroll_df[,c('dkefs', 'rbans')]) #sum

  #make an enrolled column for neuropsych - if sum is 2 
  enroll_df$enroll_np <- ifelse(enroll_df$np_count == 2, 1, 0)
  
  #identify the second date in ordered dates - i.e., when enrollment for np criteria is met
  np_dates <- c('dkefs_date', 'rbans_date')
  enroll_df$enroll_np_date <- NA
  for (n in 1:nrow(enroll_df)){
    dates <- enroll_df[n, np_dates] # pull out NP assessment dates
    dates <- dates[order(dates)] # order dates
      if (length(dates[!is.na(dates)]) == 2) { # if there are 2 assesments
        enroll_df$enroll_np_date[n] <- dates[[2]]   # pull out the second assessment date
      } else {
        enroll_df$enroll_np_date[n] <- NA         # otherwise print 'NA'
      }
    }

  #determine if np criteria was met this month
  enroll_df$enroll_np_date <- as.Date(enroll_df$enroll_np_date, origin = "1970-01-01") #turn back into date format
  enroll_df$enroll_np_mth <- as.character(substr(enroll_df$enroll_np_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_np_mthT <- enroll_df$enroll_np_mth %in% enroll_df$currentYm_str #logical T or F- was criteria met this month?

  #determine if enrollment criteria is met, i.e., at least 2/3 of mri, blood, and np completed
  enroll_df$enroll <- rowSums(enroll_df[,c('enroll_mri', 'enroll_bld', 'enroll_np')], na.rm = T) #calculate sum
  enroll_df$enroll <- ifelse(enroll_df$enroll >= 2, 1, 0)
  
  #determine date of 2/3 of mri, blood, and psy completed
  enroll_dates <- c('enroll_mri_date','enroll_bld_date', 'enroll_np_date')
  enroll_df$enroll_date <- NA
  for (n in 1:nrow(enroll_df)){
    dates <- enroll_df[n, enroll_dates] # pull out component dates
    dates <- dates[order(dates)] # order dates
      if (length(dates[!is.na(dates)]) >= 2) { # if there are 2 or more components
        enroll_df$enroll_date[n] <- dates[[2]]   # pull out the second component dates
      } else {
        enroll_df$enroll_date[n] <- NA         # otherwise print 'NA'
      }
    }
  enroll_df$enroll_date <- as.Date(enroll_df$enroll_date, origin = "1970-01-01") #turn back into date format

#determine if enrollment was met this month
  enroll_df$enroll_mth <- as.character(substr(enroll_df$enroll_date, 1, 7)) #store month and year, as character
  enroll_df$enroll_mthT <- enroll_df$enroll_mth %in% enroll_df$currentYm_str #logical T or F- was criteria met this month?

}
```






